[package]
edition = "2021"
name = "cort"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
lazy_static = {version = "1.4"}
libc = "0.2"
nix = "0.23"
tracing = "0.1"
tracing-subscriber = "0.2"

[build-dependencies]
cbindgen = "0.20"
