[package]
edition = "2021"
name = "cort"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = {version = "1.4", features = ["spin_no_std"]}
tracing = "0.1"
tracing-subscriber = "0.2"
