[package]
edition = "2021"
name = "cort"
version = "0.1.0"

[lib]
crate-type = ["staticlib"]

[dependencies]
lazy_static = {version = "1.4", features = ["spin_no_std"]}
# riscv = "0.7"

[build-dependencies]
cbindgen = "0.20"
