# https://doc.rust-lang.org/nightly/rustc/platform-support.html
# Bare RISC-V (riscv64gc = RV64IMAFDC ISA)

[build]
target = "riscv64gc-unknown-linux-gnu"
# Static feature is for run on qemu.
rustflags = ["-C", "target-feature=+crt-static"]

[test]
rustflags = ["-C", "target-feature=+crt-static"]
target = "riscv64gc-unknown-linux-gnu"

[target.riscv64gc-unknown-linux-gnu]
ar = "riscv64-linux-gnu-ar"
linker = "riscv64-linux-gnu-gcc"
runner = "qemu-riscv64"
