#ifndef cort_h
#define cort_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>

#define KILOBYTE 1024

#define MEGABYTE (1024 * KILOBYTE)

typedef struct CalleeSaved {
  uintptr_t rsp;
  uintptr_t r15;
  uintptr_t r14;
  uintptr_t r13;
  uintptr_t r12;
  uintptr_t rbx;
  uintptr_t rbp;
} CalleeSaved;

extern void uthread_switch(const struct CalleeSaved *prev, const struct CalleeSaved *next);

void spawn(void (*f)(void));

void yield_now(void);

void t_return(void);

void schedule(void);

#endif /* cort_h */
